# Generated by Django 3.0.5 on 2021-03-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='release',
        ),
        migrations.RemoveField(
            model_name='song',
            name='time',
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(default='未知', max_length=50, verbose_name='专辑'),
        ),
        migrations.AlterField(
            model_name='song',
            name='img',
            field=models.ImageField(blank=True, upload_to='songImg', verbose_name='歌曲图片'),
        ),
        migrations.AlterField(
            model_name='song',
            name='singer',
            field=models.CharField(default='未知', max_length=50, verbose_name='歌手'),
        ),
    ]
