# Generated by Django 3.0.5 on 2021-03-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210324_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.FileField(blank=True, upload_to='songLyric', verbose_name='歌词'),
        ),
    ]
