# Generated by Django 3.0.5 on 2021-03-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20210324_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='time',
            field=models.CharField(default='0:00', max_length=10, verbose_name='时长'),
        ),
    ]
